#!/bin/sh
### BEGIN INIT INFO
# Provides:          musicbox
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop musicbox server
### END INIT INFO

DEAMON=/root/musicbox/musicbox.js
LOG=/var/log/musicbox.log
PID=/var/run/musicbox.pid

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
 start)
  forever start -l $LOG --pidFile $PID -a $DEAMON
  ;;
 stop)
  forever stop --pidFile $PID $DEAMON
  ;;
 restart)
  forever restart -l $LOG --pidFile $PID -a $DEAMON
  ;;
  *)
  echo "Usage: /etc.init.d/node {start|stop|restart}"
  exit 1
  ;;
esac